name: lando-php
events:
  post-start:
    - defaults: php -i | grep memory_limit | grep -e "-1"
services:
  defaults:
    type: php
  cli:
    type: php
    composer_version: false
    via: cli
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
  cliworker:
    type: php
    composer_version: false
    via: cli
    command: sleep infinity
  cliold:
    type: php:5.6
    composer_version: false
    via: cli
  custom:
    type: php:7.1
    composer_version: false
    via: nginx
    ssl: true
    xdebug: true
    webroot: web
    config:
      php: config/php.ini
    overrides:
      image: devwithlando/php:7.1-fpm-2
      environment:
        DUALBLADE: maxim
        OTHER: thing
  custom_nginx:
    build_as_root:
      - mkdir -p /app/test && touch /app/test/managed_build_step
    overrides:
      environment:
        MORE: things
        OTHER: stuff
  custom74:
    type: php:7.4
    composer_version: false
  composer:
    type: php:7.0
    composer_version: "2.0.2"
    composer:
      phpunit/phpunit: "*"
  withnode:
    type: php:custom
    composer_version: false
    via: cli
    overrides:
      image: lando/php:7.4-with-node12
      build:
        context: ./
        dockerfile: Dockerfile.node
tooling:
  php:
    service: defaults
  node:
    service: :host
    options:
      host:
        description: The service to use
        default: cli
        alias:
          - h
